version: '2'
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090

  demo_api:
    build:
      context: .
    image: demo_api
    volumes:
      - .:/go/src/github.com/wwgberlin/go-monitoring-exercise
    ports:
      - "8080:8080"
